### ISSUE TITLE
PS4 files support

### ISSUE THREAD

**Issue by BanhMi939** [SolSaint/Frostpunk-Binfont-convert#1]
Phiền bác thêm một lần nữa, hiện tool không hỗ trợ file binfont của ps4. Mong bác xem qua. https://easyupload.io/s5els5

**Comment by systemsiteseason** [comment]
mình thấy mấy file binfont đó đều mất phần bitmap rồi, không đầy đủ, chỉ chứa phần mapping thôi. bạn nên tìm các file liên quan đến file binfont. hoặc xem kĩ trong thư mục font có chứa thêm gì không để có hướng giải quyết.

**Comment by BanhMi939** [comment]
Thế thì lạ quá, khi mình lấy 5 file font này từ bản việt hóa của bản pc qua thì vào game các chữ hiển thị sẽ mất hết. V để mình up cả folder common cho bác xem thử. https://easyupload.io/ft0co4
![image](https://user-images.githubusercontent.com/106416065/180650521-88807113-33c6-445c-9488-99b80a790f2d.png)

**Comment by BanhMi939** [comment]
Có gì bác cho mình xin discord để tiện học hỏi bác với nhé, thanks bác nhiều.

**Comment by systemsiteseason** [comment]
không có gì ngoài mapping. bạn thử extract hết game ra và điều tra từ đầu. có thể bitmap nó nằm ở một file riêng biệt. memmo_haianh97#8871

**Comment by BanhMi939** [comment]
à bác Hải anh bên viethoagame.
